import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
  {children}

  <footer
  style={{
    marginTop: "40px",
    padding: "20px",
    textAlign: "center",
    fontSize: "14px",
    color: "#666",
  }}
>
  © {new Date().getFullYear()} SeatingChartCreator ·{" "}
  <a href="/privacy" style={{ color: "#666", textDecoration: "underline" }}>
    Privacy
  </a>{" "}
  ·{" "}
  <a href="/about" style={{ color: "#666", textDecoration: "underline" }}>
    About
  </a>
</footer>
</body>
    </html>
  );
}
